title: Narender Kumar
description: > # this means to ignore newlines until "baseurl:"
  Narender's Personal Blog Site.
  More Posts coming soon.

baseurl: "/"
permalink: ':title/'
url: "https://narender.is-a.dev" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Narender Kumar
author-img: {{site.baseurl}}/assets/img/narender.jpg
about-author: > # this means to ignore newlines until "social-twitter:"
  Experienced developer having first hand experience building scalable, distributed software applications for various domains spanning across application security, eCommerce, productivity, healthcare, financial services and insurance.
  Skilled in Java, Web Services, Spring, Hibernate, JavaScript, NodeJS, React, AWS and related tech stack. 
  Strong professional with expertise in web/cloud applications, microservices, and real time applications. 
  Avid explorer with a demonstrated history in research and development.
social-twitter: nkkize
social-github: nkkize 
social-linkedin: nkkize
social-email: "nk.snat@gmail.com"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
