title: Narender Kumar
description: > # this means to ignore newlines until "baseurl:"
  Narender's Personal Blog Site.
  More Posts coming soon.

baseurl: "/"
permalink: ':title/'
url: "https://narender.is-a.dev" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Narender Kumar
author-img: narender.jpg
about-author: I am a ful stack developer focusing on application development. Always hungry to keep learning. # add description
social-twitter: "https://twitter.com/nkkize"
social-github: nkkize 
social-linkedin: "https://www.linkedin.com/in/nkkize/"
social-email: "nk.snat@gmail.com"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
